/**
 * AIOBS Core Type Definitions
 * Central type system for the AI Observability Hub
 */

// Re-export all types from common (base types used everywhere)
export * from './common';

// Re-export metrics types
export * from './metrics';

// Re-export cognitive types
export * from './cognitive';

// Re-export causal types (contains canonical EvidenceType, AffectedResource, ProjectedImpact)
export * from './causal';

// Re-export governance types, excluding duplicates (EvidenceType, RetentionPolicy)
export {
  AuditEntry,
  AuditableAction,
  AuditActionType,
  AuditCategory,
  ExecutionContext,
  ActionOutcome,
  ErrorDetails,
  ChangeRecord,
  AuditTrail,
  AuditQuery,
  ComplianceFramework,
  ComplianceFrameworkType,
  ComplianceControl,
  AssessmentCriterion,
  EvidenceRequirement,
  RequirementMapping,
  ComplianceAssessment,
  AssessmentScope,
  ComplianceStatus,
  ControlAssessment,
  CollectedEvidence,
  CriterionResult,
  ComplianceGap,
  ComplianceFinding,
  Attestation,
  RemediationPlan,
  RemediationItem,
  AuditPack,
  AIActClassification,
  AIActRiskLevel,
  ClassificationBasis,
  AIActRequirement,
  AccountabilityChain,
  Decision,
  ResponsibilityLink,
  Approval,
} from './governance';

// Re-export incidents types, excluding duplicates (AffectedResource, BusinessImpact, SLOImpact)
export {
  AIIncident,
  IncidentClassification,
  AIIncidentType,
  IncidentCategory,
  IncidentStatus,
  IncidentPriority,
  IncidentSeverity,
  ExternalReference,
  IncidentImpact,
  UserImpact,
  TechnicalImpact,
  AffectedSLO,
  SLIBreach,
  IncidentResponse,
  Responder,
  ResponderRole,
  ResponseTimelineEntry,
  TimelineEntryType,
  ResponseAction,
  ActionType,
  Communication,
  RunbookExecution,
  RunbookStepExecution,
  DetectionRule,
  DetectionTrigger,
  AnomalyConfig,
  IncidentTemplate,
  DeduplicationConfig,
  DetectedAnomaly,
  AnomalyType,
  PostMortem,
  PostMortemTimelineEntry,
  PostMortemRootCause,
  PostMortemAction,
  IncidentWorkflow,
  WorkflowStage,
  StageCondition,
  RequiredAction,
  WorkflowAutomation,
  EscalationPolicy,
  EscalationLevel,
  ResilienceScore,
  ResilienceComponent,
  ResilienceFactor,
  ResilienceRecommendation,
} from './incidents';

// Re-export SLO types
export * from './slo';

// Re-export tenant types, excluding RetentionPolicy (conflicts with governance)
export {
  Tenant,
  Organization,
  TenantContact,
  TenantStatus,
  TenantSubscription,
  SubscriptionPlan,
  PricingModel,
  PricingTier,
  BillingConfig,
  Address,
  ResourceQuotas,
  FeatureEntitlements,
  TenantConfig,
  GeneralConfig,
  BrandingConfig,
  SecurityConfig,
  AuthMethod,
  SSOConfig,
  DataClassification,
  IntegrationsConfig,
  IntegrationConfig,
  WebhookConfig,
  RetryPolicy,
  NotificationSettings,
  QuietHours,
  DataConfig,
  ExportConfig,
  AnonymizationConfig,
  IsolationConfig,
  IsolationLevel,
  DatabaseIsolation,
  ComputeIsolation,
  ComputeResourceLimits,
  NetworkIsolation,
  EdgeDeployment,
  EdgeLocation,
  EdgeConfig,
  EdgeCapabilities,
  EdgeStorageConfig,
  OfflineModeConfig,
  EdgeSyncConfig,
  EdgeDataType,
  SyncFilter,
  EdgeStatus,
  SyncStatus,
  EdgeHealth,
  DeploymentMode,
  DeploymentType,
  DeploymentConfig,
  DataResidencyConfig,
  UsageMetrics,
  ResourceUsage,
  ApiUsage,
  FeatureUsage,
  CostAllocation,
  OnboardingStatus,
  OnboardingStep,
} from './tenant';

// Re-export game-changer types, excluding duplicates (SLOImpact, BusinessImpact, ProjectedImpact)
export {
  // AI Request Cost Prediction
  AIRequest,
  CostPrediction,
  ModelCostAlternative,
  ModelSelection,
  ModelArbitrage,
  Budget,
  BudgetScope,
  FallbackStrategy,
  // Carbon-Aware Scheduling
  CarbonIntensity,
  CarbonForecast,
  BatchJob,
  JobConstraints,
  ScheduledJob,
  ScheduleSlot,
  RegionRecommendation,
  RegionAlternative,
  CarbonCertificate,
  CarbonBreakdown,
  // Drift Forecasting
  DriftForecast,
  DriftForecastPoint,
  DriftRecommendation,
  ImpactSimulation,
  BusinessImpactEstimate,
  PreventiveAction,
  RetrainingPlan,
  DataRequirement,
  // Multi-Agent Orchestration
  AgentTopologyGraph,
  AgentNode,
  AgentConnection,
  ToolNode,
  DecisionTrace,
  DecisionStep,
  AnomalyReport,
  AgentAnomaly,
  ABComparison,
  OrchestrationStrategy,
  ComparisonMetrics,
  // Security
  InjectionDetection,
  DataLeakScan,
  DataLeak,
  SecurityRiskScore,
  RiskFactor,
  SecurityRecommendation,
  JailbreakDetection,
  // Revenue Attribution
  RevenueAttribution,
  RevenueBreakdown,
  MetricKPICorrelation,
  ModelImprovement,
  ROICalculation,
  CostComponent,
  BenefitComponent,
  // Prompt Engineering
  PromptExperiment,
  PromptVariant,
  ExperimentMetric,
  ExperimentAnalysis,
  VariantResult,
  // Shadow Deployment
  ShadowDeployment,
  ModelConfig,
  ModelComparison,
  TestSetInfo,
  ModelComparisonResult,
} from './game-changer';
